domain = {
//  fixed = example.com.com
//  format = %i%i.wildcardexample.com
//  file = assets/cloudflare-radar_top-1000-domains_xyz.csv
}

runs = {
  DNS = {
    servers = [
      // Cloudflare
      "1.1.1.1", "1.0.0.1", "2606:4700:4700::1111", "2606:4700:4700::1001",
      // Google
      "8.8.8.8", "8.8.4.4", "2001:4860:4860::8888", "2001:4860:4860::8844",

      // add your own
    ]
  },
  DoT = {
    servers = [
      // Cloudflare
      one.one.one.one
      // Google
      dns.google

      // add your own
    ]
  },
}
